# Generated by Django 5.1.4 on 2025-02-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=None, max_length=6, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
