# Generated by Django 5.1.4 on 2025-02-25 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='tickets/')),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.attendee')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_pdfs', to='client.purchase')),
            ],
        ),
    ]
