# Generated by Django 5.1.4 on 2025-03-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_ticketpdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='ticket_pdf',
        ),
        migrations.RemoveField(
            model_name='ticketpdf',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='purchase',
            name='ticket_pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ticketpdf',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketpdf',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ticketpdf',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
