# Generated by Django 5.1.4 on 2025-03-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_purchase_ticket_pdf_remove_ticketpdf_pdf_file_and_more'),
    ]

    operations = [
    ]
