# Generated by Django 5.1.4 on 2025-03-05 19:53
from django.db import migrations, models

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20250305_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpdf',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketpdf',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
