# Generated by Django 5.1.4 on 2025-03-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_add_exit_time_to_ticketpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
