# Generated by Django 5.1.4 on 2025-04-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_purchase_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpdf',
            name='exit_reason',
            field=models.CharField(choices=[('normal', 'Normal Exit'), ('injured', 'Injured'), ('emergency', 'Emergency')], default='normal', max_length=50),
        ),
        migrations.AddField(
            model_name='ticketpdf',
            name='injury_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
