# Generated by Django 5.1.4 on 2025-04-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_ticketpdf_exit_reason_ticketpdf_injury_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_screenshot',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
